### PR TITLE
Feat/webtypes default icon

### LINKED ISSUE #99: [jet-brains-integration] feature request, option to set the default-icon for web-types.json
Displaying your icon on the code completion list in intellij is a nice feature.

### PR DESCRIPTION
**Pull request by veith**
option for adding a default-icon added.

closes #99

### CODE REVIEW

**Comment by break-stuff** [comment]
Does the icon need to be included in the project or can it reference a URL?

**Comment by break-stuff** [comment]
Would you be willing to update the `README.md` with information about this?

**Comment by veith** [comment]
During adding the documentation i spotted that `referencesTemplate` is wrong documented. The `Options` type wants a `referenceTemplate`. And after playing with this option, i realised that the code is never called.

I will file another issue on this.

**Comment by veith** [comment]
> Would you be willing to update the `README.md` with information about this?

done

**Review by break-stuff — APPROVED** [review]

**Comment by veith** [comment]
@break-stuff Is there any other actions from my side expected before merge?

**Comment by break-stuff** [comment]
I think we're good! Thank you!

**Pull request merged**
